### ISSUE TITLE
support swift

### ISSUE THREAD

**Issue by boxstore** [rollout/rollout.io-ios#112]
hi, is rollout injected into process using DYLD_INSERT_LIBRARIES ?
it's safe ?

from https://developer.apple.com/library/content/documentation/Xcode/Conceptual/RN-Xcode-Archive/Chapters/xc7_release_notes.html
_Multiple components of Xcode 7 run with library validation enabled in order to prevent exploitation by malicious code. Any code that interposes system libraries or that is injected into process using DYLD_INSERT_LIBRARIES may cause problems when you are running Xcode 7.

You are advised to either remove software that interposes system libraries or is injected into processes using DYLD_INSERT_LIBRARIES from your system, or contact the vendor of such software for an update. (22366994)_

**Comment by ekeren** [comment]
@boxstore - We are using DYLD_INSERT_LIBRARIES when running swiftc in order to hijack the open system call and enter source code instrumentation phase, this is exactly like changing the file prior to the compilation phase. 

This is described in our under the hood blog [here](https://blog.rollout.io/swift-method-swizzling/)

The mechanism is working on all xcode version, and If apple choose to disable DYLD_INSERT_LIBRARIES on swiftc we will replace the mechanism with another one.

Hope this answer your concern.
