### ISSUE TITLE
Add support to SWIFT

### ISSUE THREAD

**Issue by ekeren** [rollout/rollout.io-ios#14]

**Comment by Armenm** [comment]
+1

**Comment by jrmgx** [comment]
+1

**Comment by freak4pc** [comment]
+1

**Comment by liviur** [comment]
+1 :)

**Comment by genadyo** [comment]
+1

**Comment by imoldman** [comment]
+1

**Comment by kapellanos** [comment]
+1

**Comment by Luke47** [comment]
+1

**Comment by natanrolnik** [comment]
+1

**Comment by javikr** [comment]
+1

**Comment by crazyjooe** [comment]
+1

**Comment by JohnWong** [comment]
+1

**Comment by mosaic6** [comment]
+1

**Comment by SASDOE** [comment]
+1

**Comment by zammbi** [comment]
Is there a way to ignore the build error "This Rollout.io version does not support Swift"? We have very little swift code in our project and don't care if it doesn't support it.

**Comment by silyevsk** [comment]
@zammbi - Actually, the error you are seeing is not about the support for swift code. There's an issue with Rollout 0.8 not working at all if there's a swift file in the target. We are working to solve it, but for now, if your target contains swift files, you will have to downgrade the SDK to the last 0.7 version (0.7.3 at the moment).

**Comment by cyril94440** [comment]
+1000

**Comment by webmagnets** [comment]
me three

**Comment by antigp** [comment]
+1

**Comment by chechusiscar** [comment]
+1

**Comment by velvetz7** [comment]
+1

**Comment by ekeren** [comment]
If your project is mainly objc and have some swift code inside you can use version 0.8.7. 

Unfortunately, due to changes in swift implementation we will need to wait a bit with swift support, till the swift 2.0 will be stable.

**Comment by mervarnold** [comment]
+1

**Comment by rynwola** [comment]
+1

**Comment by zeroelink** [comment]
+1

**Comment by shmakovigor** [comment]
+1

**Comment by trongcuong1710** [comment]
+1

**Comment by Kluskey** [comment]
+1

**Comment by hirenpanchal1608** [comment]
+111111111

**Comment by dwaynewilliams** [comment]
+1

**Comment by jamesanse** [comment]
+1

**Comment by bfcatch** [comment]
+1

**Comment by trixmasta** [comment]
+1

**Comment by AOrumbaev** [comment]
+1

**Comment by acegreen** [comment]
:+1:

**Comment by salvonos** [comment]
+1

**Comment by zdesiree** [comment]
+1

**Comment by oscarmorrison** [comment]
+1

**Comment by pmiaskiewicz** [comment]
+1

**Comment by coderdreamworld** [comment]
+1

**Comment by sasvarizoli** [comment]
+1

**Comment by falcon4ever** [comment]
+1

**Comment by thediary** [comment]
+1

**Comment by danielbmarques** [comment]
+1?

**Comment by iOSDevHP** [comment]
+1

**Comment by pvroosendaal** [comment]
+1

**Comment by winkelsdorf** [comment]
+1

**Comment by feeqiang** [comment]
+1

**Comment by imclean** [comment]
+1

**Comment by infinernet** [comment]
+1

**Comment by joturako** [comment]
+1

**Comment by naru** [comment]
+1

**Comment by guidomb** [comment]
:+1:

**Comment by JackoPlane** [comment]
+1

**Comment by congni** [comment]
+1

**Comment by Shakarang** [comment]
+1

**Comment by gustavogervasio** [comment]
+1

**Comment by wordisborn** [comment]
+1

**Comment by namanhams** [comment]
+1

**Comment by lquigley** [comment]
+1

**Comment by ThaoPN** [comment]
+1

**Comment by nazeehshoura** [comment]
+1

**Comment by silyevsk** [comment]
Hi,

We recently started Rollout Swift beta and are slowly accepting new beta users. If you are interested to get on the list, please fill out this form:  http://goo.gl/forms/wt3ci7ixaW

**Comment by bfcatch** [comment]
sorry to break the formation...

i seemed to have read somewhere in the faq that if the app is hybrid (having both obj-c & swift code), only obj-c patches will be supported.
is that still true please? thanks

**Comment by silyevsk** [comment]
That's true. This ticket is about Swift support, we are working on it and some Swift support is now available in the beta (you can register to it at [this form](http://goo.gl/forms/wt3ci7ixaW)).

**Comment by vshall20** [comment]
+1

**Comment by bhavukjain1** [comment]
+1

**Comment by callam** [comment]
+1

**Comment by dungntm58** [comment]
+1

**Comment by nullpixel1** [comment]
+1

**Comment by Shimi** [comment]
Hi All,

For the coming release of Swift support in Rollout we will be happy if you can take a minute to answer this [Swift version survey](https://goo.gl/forms/rPQOfGweT1c1GJ263).

**Comment by Shimi** [comment]
Hi Everyone,

I'm happy to announce that Rollout Swift support is in now in public beta.

In order to use Rollout for your Swift project you will need to:
 * login into your [Rollout account](https://app.rollout.io/) 
 * create a new app in the Rollout dashboard
 * download and run the Rollout installer
 * click on the Swift beta support checkbox and follow the instructions in the installer

More information on Swift support here:
http://support.rollout.io/docs/swift-coverage

Please do not tweet or publicly discuss Swift support until it's graduated from beta.

**Comment by Shimi** [comment]
Hi Everyone,

I'm happy to announce that Rollout Swift beta support now includes **Swift 3**

As before, In order to use Rollout for your Swift project you will need to:

- login into your [Rollout account](http://goo.gl/XqM6AP) 
- create a new app in the Rollout dashboard
- download and run the Rollout installer
- click on the Swift beta support checkbox and follow the instructions in the installer

More information on Swift support here:
http://support.rollout.io/docs/swift-coverage

Please do not tweet or publicly discuss Swift support until it's graduated from beta.

**Comment by Shimi** [comment]
@acegreen Right, you don't need to create a new app.
If you already have an app in Rollout dashboard you need to download a new installer or use the latest cocoa pods release. The instructions are in the app settings.

**Comment by Shimi** [comment]
Hi Everyone,

I'm delighted to announce that Rollout now supports Swift apps!

After months of development, testing and tweaking we've just released our official Swift support.

If you’ve been waiting for Swift support in order to try out Rollout, either create a new app and install the SDK or upgrade your existing app with the latest SDK version.

More information in our [Swift release blog post](https://blog.rollout.io/rollout-now-supports-swift)

I would like to thank all the people that tried our beta and reported issues.
