### ISSUE TITLE
Every time i run my app on Xcode files on Rollout-ios-SDK are updated and i've to commit them in my repository

### ISSUE THREAD

**Issue by AlbertoRoomi** [rollout/rollout.io-ios#47]
Every time i run my app the files called "RolloutDynamic_##" in a subfolder of Rollout-ios-SDK get updated and and inside every of this files the first line reads "// This file is auto generated by Rollout.io SDK during application build process, it should be committed to you repository as part of your code. For more info please checkout the FAQ at http://support.rollout.io"

This obviously affects the readability of every commit. Do i really need to include them every time i push a commit for my app?

**Comment by silyevsk** [comment]
Yes, you have to commit these files. Your application is compiled with this code, and if it (or a part of it) is missing, you will not be able to hot-patch your methods (or some of them). So every time there's a change in the files, it should be committed (if discarded, the code will be regenerated, but it's important to have the code in place before you archive the app, so better to just commit it every time). However, the files change only when Rollout.io finds a new method signature in your application, or when the app is built for a new architecture. We understand this is still not convenient and we will implement a better way in the future.

The related FAQ (referencing it here because it may change in the future):
http://support.rollout.io/v1.0/docs/rolloutio-installation-guide#what-are-the-files-under-auto_generated_code

**Comment by AlbertoRoomi** [comment]
Ok, thank you

**Comment by slabko** [comment]
Sounds like, if I'm ok to build the project twice, on the build server, then I don't need to commit those files. Is that right?

**Comment by silyevsk** [comment]
@slabko - That's right. You can also upgrade to our SDK 0.14 - it works without dynamic code.
