### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by YacineVC** [rollout/rollout.io-ios#87]
We just had troubles between the version 0.14.4 and 0.14.5,
where Boolean encapsulation does not seem to work the same.

In 0.14.4, a simple bool was not encapsulated the rollout object, but it was in the 0.14.5.

Is it possible to have all the changes between versions on the Git ?
Or even better, a versioned documentation ?

Thanks in advance !
Cheers

**Comment by YacineVC** [comment]
My bad, found this http://support.rollout.io/docs/change-log

Thanks to Erez ;)

**Comment by silyevsk** [comment]
Hi,

In addition to changelog, we actually do have per-API version documentation. API number is a version which is usually incremented when we change how our server side talks to the SDK. It's internal and is not really interesting, but in particular it's incremented when there are javascript interface changes. What is interesting, is that we split our documentation when we are changing this number (at least since JS support went to production). So, if your app uses an SDK of older API, you can go to that API documentation and will get the JS syntax compatible with your SDK version. The link to the versioned documentation appears at the comment in JS editor (line 2).

Regarding 0.14.4 - 0.14.5 difference - there should not be any if I remember correctly, nothing was changed in 0.14.5 except for showAlertView bug fixed. There was a BOOL-on-32bit bug fixed in 0.15 though, may be this is it. Unfortunately, bugs fixed only in SDK are not reflected in the documentation so in this case it wouldn't help anyway. I now realise that it would be helpful to alert on this bug inside the dashboard, we will think how it can be done.

**Comment by YacineVC** [comment]
Thank you for your fast reply

Indeed we had troubles with the bug fixed of Bool on 32 bit. 

To describe a bit, the production had the 0.14.5 and the debug was on 0.15

So when trying to patch we had different behavior between our versions. We assumed after that the problem was coming from the different architecture (64, 32 bits)

Regards
